on:
  pull_request:
    types: [ opened ]
name: Pull Requests
jobs:
  pullRequestHandler:
    name: Pull Request Validator
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@main
    - name: Pull Request Validator
      uses: Ash258/Scoop-GithubActions@stable-win
      env:
        GITH_EMAIL: earnestma@hotmail.com
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
